// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using YachtMarinaAPI.DAL;

#nullable disable

namespace YachtMarinaAPI.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20240421024244_init2")]
    partial class init2
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "7.0.12")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("ChatUser", b =>
                {
                    b.Property<int>("ChatsId")
                        .HasColumnType("int");

                    b.Property<int>("UsersId")
                        .HasColumnType("int");

                    b.HasKey("ChatsId", "UsersId");

                    b.HasIndex("UsersId");

                    b.ToTable("ChatUser");
                });

            modelBuilder.Entity("JourneyUser", b =>
                {
                    b.Property<int>("JourneysId")
                        .HasColumnType("int");

                    b.Property<int>("UserId")
                        .HasColumnType("int");

                    b.HasKey("JourneysId", "UserId");

                    b.HasIndex("UserId");

                    b.ToTable("JourneyUser");
                });

            modelBuilder.Entity("YachtMarinaAPI.Entities.Chat", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Chats");
                });

            modelBuilder.Entity("YachtMarinaAPI.Entities.Friend", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("AvatarUrl")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("FriendUserId")
                        .HasColumnType("int");

                    b.Property<string>("Rolename")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("UserId")
                        .HasColumnType("int");

                    b.Property<string>("Username")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("Friend");
                });

            modelBuilder.Entity("YachtMarinaAPI.Entities.Invite", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("FromUserAvatarUrl")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("FromUserId")
                        .HasColumnType("int");

                    b.Property<string>("FromUsername")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("ToUserId")
                        .HasColumnType("int");

                    b.Property<int?>("UserId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("Invites");
                });

            modelBuilder.Entity("YachtMarinaAPI.Entities.MarinaMarker", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<decimal>("Lat")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("Lng")
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("MarinaMarkers");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Lat = 53.656204624404204m,
                            Lng = 14.619229583488101m,
                            Name = "Klub Żeglarski i Motorowodny LOK Stepnica"
                        },
                        new
                        {
                            Id = 2,
                            Lat = 53.66398675567115m,
                            Lng = 14.514430078620219m,
                            Name = "Marina Trzebież"
                        },
                        new
                        {
                            Id = 3,
                            Lat = 53.72901360148618m,
                            Lng = 14.280381204084115m,
                            Name = "Marina Nowe Warpno"
                        },
                        new
                        {
                            Id = 4,
                            Lat = 53.85099465073054m,
                            Lng = 14.620618366810927m,
                            Name = "Marina Wolin"
                        },
                        new
                        {
                            Id = 5,
                            Lat = 54.134785612826235m,
                            Lng = 13.743982320596313m,
                            Name = "MARINA KRÖSLIN GmbH im BALTIC SEA RESORT"
                        },
                        new
                        {
                            Id = 6,
                            Lat = 53.92484250491297m,
                            Lng = 14.273954582044846m,
                            Name = "Marina Basen Północny"
                        },
                        new
                        {
                            Id = 7,
                            Lat = 53.89685373578024m,
                            Lng = 14.361488472458847m,
                            Name = "Marina Łunowo"
                        },
                        new
                        {
                            Id = 8,
                            Lat = 53.903619917590575m,
                            Lng = 14.436979667884126m,
                            Name = "Marina Wicko"
                        },
                        new
                        {
                            Id = 9,
                            Lat = 53.9759309937529m,
                            Lng = 14.76896098382106m,
                            Name = "Marina Kamień Pomorski"
                        },
                        new
                        {
                            Id = 10,
                            Lat = 54.00633117994754m,
                            Lng = 14.705488306339065m,
                            Name = "Przystań jachtowa w Międzywodziu"
                        },
                        new
                        {
                            Id = 11,
                            Lat = 54.039158902778766m,
                            Lng = 14.801714273149273m,
                            Name = "Przystań jachtowa Dziwnówek"
                        },
                        new
                        {
                            Id = 12,
                            Lat = 53.88047470469847m,
                            Lng = 14.426514107316752m,
                            Name = "Marina Wapnica Międzyzdroje"
                        },
                        new
                        {
                            Id = 13,
                            Lat = 53.72725538121933m,
                            Lng = 14.282705024591502m,
                            Name = "Port Jachtowy"
                        },
                        new
                        {
                            Id = 14,
                            Lat = 53.52262711436701m,
                            Lng = 14.625836954883425m,
                            Name = "Port Szczecin"
                        },
                        new
                        {
                            Id = 15,
                            Lat = 54.10418698975753m,
                            Lng = 15.084198208319565m,
                            Name = "Port Niechorze"
                        },
                        new
                        {
                            Id = 16,
                            Lat = 53.73631291899811m,
                            Lng = 14.050031728836158m,
                            Name = "Stadtanleger Ueckermünde"
                        },
                        new
                        {
                            Id = 17,
                            Lat = 54.06364878736257m,
                            Lng = 13.78154357301695m,
                            Name = "Segel Club Wolgast e.V."
                        },
                        new
                        {
                            Id = 18,
                            Lat = 54.10838422590356m,
                            Lng = 13.813029197715817m,
                            Name = "Marina and fishing port Karlshagen"
                        },
                        new
                        {
                            Id = 19,
                            Lat = 54.15049391054093m,
                            Lng = 13.757882482802255m,
                            Name = "Baltic Sea Yacht Events, Segelkatamaran"
                        },
                        new
                        {
                            Id = 20,
                            Lat = 53.844872436662364m,
                            Lng = 13.85785336911374m,
                            Name = "Gästehafen Karnin"
                        });
                });

            modelBuilder.Entity("YachtMarinaAPI.Entities.Message", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("ChatId")
                        .HasColumnType("int");

                    b.Property<string>("MessageText")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("Time")
                        .HasColumnType("datetime2");

                    b.Property<int>("UserId")
                        .HasColumnType("int");

                    b.Property<string>("Username")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("isSeen")
                        .HasColumnType("bit");

                    b.HasKey("Id");

                    b.HasIndex("ChatId");

                    b.ToTable("Messages");
                });

            modelBuilder.Entity("YachtMarinaAPI.Models.Basket", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("ClientSecret")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PaymentIntentId")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("UserId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.ToTable("Baskets");
                });

            modelBuilder.Entity("YachtMarinaAPI.Models.BasketItem", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("BasketId")
                        .HasColumnType("int");

                    b.Property<long>("Price")
                        .HasColumnType("bigint");

                    b.Property<int>("ProductId")
                        .HasColumnType("int");

                    b.Property<int>("Quantity")
                        .HasColumnType("int");

                    b.Property<DateTime?>("endDate")
                        .HasColumnType("datetime2");

                    b.Property<bool>("isLoan")
                        .HasColumnType("bit");

                    b.Property<DateTime?>("startDate")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.HasIndex("BasketId");

                    b.HasIndex("ProductId");

                    b.ToTable("BasketItem");
                });

            modelBuilder.Entity("YachtMarinaAPI.Models.Document", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Filename")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("RoleId")
                        .HasColumnType("int");

                    b.Property<string>("RoleName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("UserId")
                        .HasColumnType("int");

                    b.Property<string>("Username")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("RoleId");

                    b.HasIndex("UserId");

                    b.ToTable("Documents");
                });

            modelBuilder.Entity("YachtMarinaAPI.Models.Journey", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<decimal>("Distance")
                        .HasColumnType("decimal(18,2)");

                    b.Property<DateTime?>("EndDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Note")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("StartDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("UserId")
                        .HasColumnType("int");

                    b.Property<int>("YachtId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.ToTable("Journeys");
                });

            modelBuilder.Entity("YachtMarinaAPI.Models.Order.Order", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("OrderDate")
                        .HasColumnType("datetime2");

                    b.Property<int>("OrderStatus")
                        .HasColumnType("int");

                    b.Property<string>("PaymentIntentId")
                        .HasColumnType("nvarchar(max)");

                    b.Property<long>("Subtotal")
                        .HasColumnType("bigint");

                    b.Property<int>("UserId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.ToTable("Orders");
                });

            modelBuilder.Entity("YachtMarinaAPI.Models.Product", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Brand")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal>("Length")
                        .HasColumnType("decimal(18,2)");

                    b.Property<long>("LoanPricePerDay")
                        .HasColumnType("bigint");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PictureUrl")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<long>("Price")
                        .HasColumnType("bigint");

                    b.Property<string>("PublicId")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("QuantityInStock")
                        .HasColumnType("int");

                    b.Property<string>("Type")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("YearOfProduction")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.ToTable("Products");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Brand = "Antila",
                            Description = "Jacht Antila 30 wyprodukowany w 2021 roku o długości 9.45m.",
                            Length = 9.45m,
                            LoanPricePerDay = 1000L,
                            Name = "Antila 30",
                            PictureUrl = "/images/products/jacht1.jpg",
                            Price = 400000L,
                            QuantityInStock = 5,
                            Type = "Żaglowo-motorowy",
                            YearOfProduction = 2021
                        },
                        new
                        {
                            Id = 2,
                            Brand = "Antila",
                            Description = "Jacht Antila 33 wyprodukowany w 2017 roku o długości 9.60m.",
                            Length = 9.60m,
                            LoanPricePerDay = 900L,
                            Name = "Antila 33",
                            PictureUrl = "/images/products/jacht2.jpg",
                            Price = 300000L,
                            QuantityInStock = 4,
                            Type = "Żaglowo-motorowy",
                            YearOfProduction = 2017
                        },
                        new
                        {
                            Id = 3,
                            Brand = "Antila",
                            Description = "Jacht Antila 28.2 wyprodukowany w 2023 roku o długości 8.85m.",
                            Length = 8.85m,
                            LoanPricePerDay = 700L,
                            Name = "Antila 28.2",
                            PictureUrl = "/images/products/jacht3.jpg",
                            Price = 300000L,
                            QuantityInStock = 3,
                            Type = "Żaglowo-motorowy",
                            YearOfProduction = 2023
                        },
                        new
                        {
                            Id = 4,
                            Brand = "Antila",
                            Description = "Jacht Antila 27 wyprodukowany w 2022 roku o długości 9.45m.",
                            Length = 9.45m,
                            LoanPricePerDay = 600L,
                            Name = "Antila 27",
                            PictureUrl = "/images/products/jacht4.jpg",
                            Price = 130000L,
                            QuantityInStock = 4,
                            Type = "Żaglowo-motorowy",
                            YearOfProduction = 2022
                        },
                        new
                        {
                            Id = 5,
                            Brand = "Delphia",
                            Description = "Jacht Delphia 33 MC wyprodukowany w 2014 roku o długości 9.95m.",
                            Length = 9.95m,
                            LoanPricePerDay = 700L,
                            Name = "Delphia 33 MC",
                            PictureUrl = "/images/products/jacht5.jpg",
                            Price = 220000L,
                            QuantityInStock = 2,
                            Type = "Żaglowo-motorowy",
                            YearOfProduction = 2014
                        },
                        new
                        {
                            Id = 6,
                            Brand = "Laguna",
                            Description = "Jacht Laguna 26 wyprodukowany w 2020 roku o długości 7.6m.",
                            Length = 7.6m,
                            LoanPricePerDay = 400L,
                            Name = "Laguna 26",
                            PictureUrl = "/images/products/jacht6.jpg",
                            Price = 140000L,
                            QuantityInStock = 3,
                            Type = "Żaglowo-motorowy",
                            YearOfProduction = 2020
                        },
                        new
                        {
                            Id = 7,
                            Brand = "Laguna",
                            Description = "Jacht Laguna 30 wyprodukowany w 2011 roku o długości 8.85m.",
                            Length = 8.85m,
                            LoanPricePerDay = 500L,
                            Name = "Laguna 30",
                            PictureUrl = "/images/products/jacht7.jpg",
                            Price = 150000L,
                            QuantityInStock = 5,
                            Type = "Żaglowo-motorowy",
                            YearOfProduction = 2011
                        },
                        new
                        {
                            Id = 8,
                            Brand = "Mariner",
                            Description = "Jacht Mariner 20 wyprodukowany w 2011 roku o długości 5.98m.",
                            Length = 5.98m,
                            LoanPricePerDay = 200L,
                            Name = "Mariner 20",
                            PictureUrl = "/images/products/jacht8.jpg",
                            Price = 35000L,
                            QuantityInStock = 6,
                            Type = "Żaglowo-motorowy",
                            YearOfProduction = 2011
                        },
                        new
                        {
                            Id = 9,
                            Brand = "Mariner",
                            Description = "Jacht Mariner 24 wyprodukowany w 2013 roku o długości 7.62m.",
                            Length = 7.62m,
                            LoanPricePerDay = 2500L,
                            Name = "Mariner 24",
                            PictureUrl = "/images/products/jacht9.jpg",
                            Price = 50000L,
                            QuantityInStock = 3,
                            Type = "Żaglowo-motorowy",
                            YearOfProduction = 2013
                        },
                        new
                        {
                            Id = 10,
                            Brand = "Mariner",
                            Description = "Jacht Mariner 31 wyprodukowany w 2019 roku o długości 9.45m.",
                            Length = 9.45m,
                            LoanPricePerDay = 500L,
                            Name = "Mariner 31",
                            PictureUrl = "/images/products/jacht10.jpg",
                            Price = 160000L,
                            QuantityInStock = 4,
                            Type = "Żaglowo-motorowy",
                            YearOfProduction = 2019
                        },
                        new
                        {
                            Id = 11,
                            Brand = "Phila",
                            Description = "Jacht Phila 880 wyprodukowany w 2014 roku o długości 8.80m.",
                            Length = 8.80m,
                            LoanPricePerDay = 300L,
                            Name = "Phila 880",
                            PictureUrl = "/images/products/jacht11.jpg",
                            Price = 130000L,
                            QuantityInStock = 2,
                            Type = "Żaglowo-motorowy",
                            YearOfProduction = 2014
                        },
                        new
                        {
                            Id = 12,
                            Brand = "Phila",
                            Description = "Jacht Phila 900 wyprodukowany w 2016 roky o długości 9.52m.",
                            Length = 9.52m,
                            LoanPricePerDay = 400L,
                            Name = "Phila 900",
                            PictureUrl = "/images/products/jacht12.jpg",
                            Price = 200000L,
                            QuantityInStock = 2,
                            Type = "Żaglowo-motorowy",
                            YearOfProduction = 2016
                        },
                        new
                        {
                            Id = 13,
                            Brand = "Phobos",
                            Description = "Jacht Phobos 21 wyprodukowany w 2012 roku o długości 6.18m.",
                            Length = 6.18m,
                            LoanPricePerDay = 350L,
                            Name = "Phobos 21",
                            PictureUrl = "/images/products/jacht13.jpg",
                            Price = 100000L,
                            QuantityInStock = 3,
                            Type = "Żaglowo-motorowy",
                            YearOfProduction = 2012
                        },
                        new
                        {
                            Id = 14,
                            Brand = "Phobos",
                            Description = "Jacht Phobos 25 wyprodukowany w 2010 roku o długości 7.72m",
                            Length = 7.72m,
                            LoanPricePerDay = 400L,
                            Name = "Phobos 25",
                            PictureUrl = "/images/products/jacht14.jpg",
                            Price = 150000L,
                            QuantityInStock = 4,
                            Type = "Żaglowo-motorowy",
                            YearOfProduction = 2010
                        },
                        new
                        {
                            Id = 15,
                            Brand = "Sasanka",
                            Description = "Jacht Sasanka 660 wyprodukowany w 2006 roku o długości 6.60m.",
                            Length = 6.60m,
                            LoanPricePerDay = 300L,
                            Name = "Sasanka 660",
                            PictureUrl = "/images/products/jacht15.jpg",
                            Price = 35000L,
                            QuantityInStock = 5,
                            Type = "Żaglowo-motorowy",
                            YearOfProduction = 2006
                        },
                        new
                        {
                            Id = 16,
                            Brand = "Scandinavia",
                            Description = "Jacht Scandinavia 27 wyprodukowany w 2022 roku o długości 7.85m.",
                            Length = 7.85m,
                            LoanPricePerDay = 300L,
                            Name = "Scandinavia 27",
                            PictureUrl = "/images/products/jacht16.jpg",
                            Price = 95000L,
                            QuantityInStock = 1,
                            Type = "Żaglowo-motorowy",
                            YearOfProduction = 2011
                        },
                        new
                        {
                            Id = 17,
                            Brand = "Sedna",
                            Description = "Jacht Sedna 26 wyprodukowany w 2016 roku o długości 7.90m.",
                            Length = 7.90m,
                            LoanPricePerDay = 300L,
                            Name = "Sedna 26",
                            PictureUrl = "/images/products/jacht17.jpg",
                            Price = 165000L,
                            QuantityInStock = 2,
                            Type = "Żaglowo-motorowy",
                            YearOfProduction = 2016
                        },
                        new
                        {
                            Id = 18,
                            Brand = "Sedna",
                            Description = "Jacht Sedna 30 wyprodukowany w 2020 roku o długości 9m",
                            Length = 9m,
                            LoanPricePerDay = 400L,
                            Name = "Sedna 30",
                            PictureUrl = "/images/products/jacht18.jpg",
                            Price = 250000L,
                            QuantityInStock = 3,
                            Type = "Żaglowo-motorowy",
                            YearOfProduction = 2020
                        },
                        new
                        {
                            Id = 19,
                            Brand = "TES",
                            Description = "Jacht TES 246 Versus wyprodukowany w 2018 roku o długości 7.49m",
                            Length = 7.49m,
                            LoanPricePerDay = 310L,
                            Name = "TES 246 Versus",
                            PictureUrl = "/images/products/jacht19.jpg",
                            Price = 200000L,
                            QuantityInStock = 1,
                            Type = "Żaglowo-motorowy",
                            YearOfProduction = 2017
                        },
                        new
                        {
                            Id = 20,
                            Brand = "TES",
                            Description = "Jacht TES 32 Dreamer wyprodukowany w 2024 roku o długości 9.69m.",
                            Length = 9.69m,
                            LoanPricePerDay = 450L,
                            Name = "TES 32 Dreamer",
                            PictureUrl = "/images/products/jacht20.jpg",
                            Price = 325000L,
                            QuantityInStock = 1,
                            Type = "Żaglowo-motorowy",
                            YearOfProduction = 2024
                        },
                        new
                        {
                            Id = 21,
                            Brand = "Sportina",
                            Description = "Jacht Sportina 680 wyprodukowany w 2006 roku o długości 6.80m.",
                            Length = 6.80m,
                            LoanPricePerDay = 300L,
                            Name = "Sportina 680",
                            PictureUrl = "/images/products/jacht21.jpg",
                            Price = 30000L,
                            QuantityInStock = 5,
                            Type = "Żaglowo-motorowy",
                            YearOfProduction = 2006
                        },
                        new
                        {
                            Id = 22,
                            Brand = "Sportina",
                            Description = "Jacht Sportina 760 wyprodukowany w 2003 roku o długości 7.90m.",
                            Length = 7.60m,
                            LoanPricePerDay = 400L,
                            Name = "Sportina 760 ",
                            PictureUrl = "/images/products/jacht22.jpg",
                            Price = 55000L,
                            QuantityInStock = 6,
                            Type = "Żaglowo-motorowy",
                            YearOfProduction = 2003
                        },
                        new
                        {
                            Id = 23,
                            Brand = "BALT",
                            Description = "Jacht BALT 818 Tytan wyprodukowany w 2020 roku o długości 7.30m.",
                            Length = 7.30m,
                            LoanPricePerDay = 700L,
                            Name = "BALT 818 Tytan",
                            PictureUrl = "/images/products/jacht23.jpg",
                            Price = 350000L,
                            QuantityInStock = 3,
                            Type = "Motorowy",
                            YearOfProduction = 2020
                        },
                        new
                        {
                            Id = 24,
                            Brand = "Futura",
                            Description = "Jacht Futura 900 wyprodukowany w 2017 roku o długości 9m.",
                            Length = 9.00m,
                            LoanPricePerDay = 500L,
                            Name = "Futura 900",
                            PictureUrl = "/images/products/jacht24.jpg",
                            Price = 220000L,
                            QuantityInStock = 1,
                            Type = "Motorowy",
                            YearOfProduction = 2017
                        },
                        new
                        {
                            Id = 25,
                            Brand = "Janmor",
                            Description = "Jacht Janmor 700 wyprodukowany w 2017 roku o długości 7.08m.",
                            Length = 7.08m,
                            LoanPricePerDay = 450L,
                            Name = "Janmor 700",
                            PictureUrl = "/images/products/jacht25.jpg",
                            Price = 185000L,
                            QuantityInStock = 2,
                            Type = "Motorowy",
                            YearOfProduction = 2017
                        },
                        new
                        {
                            Id = 26,
                            Brand = "Stillo",
                            Description = "Jacht Stillo 30 wyprodukowany w 2021 roku o długości 9.1m.",
                            Length = 9.1m,
                            LoanPricePerDay = 1000L,
                            Name = "Stillo 30",
                            PictureUrl = "/images/products/jacht26.jpg",
                            Price = 450000L,
                            QuantityInStock = 2,
                            Type = "Motorowy",
                            YearOfProduction = 2021
                        },
                        new
                        {
                            Id = 27,
                            Brand = "Sun camper",
                            Description = "Jacht Sun Camper 35 Flybridge wyprodukowany w 2018 roku o długości 9.05m.",
                            Length = 9.05m,
                            LoanPricePerDay = 1200L,
                            Name = "Sun Camper 35 Flybridge",
                            PictureUrl = "/images/products/jacht27.jpg",
                            Price = 400000L,
                            QuantityInStock = 1,
                            Type = "Motorowy",
                            YearOfProduction = 2018
                        },
                        new
                        {
                            Id = 28,
                            Brand = "Conrad",
                            Description = "Jacht Conrad 45 wyprodukowany w 1976 roku o długości 13.84m.",
                            Length = 13.84m,
                            LoanPricePerDay = 500L,
                            Name = "Conrad 45",
                            PictureUrl = "/images/products/jacht28.jpg",
                            Price = 120000L,
                            QuantityInStock = 1,
                            Type = "Żaglowo-motorowy",
                            YearOfProduction = 1976
                        },
                        new
                        {
                            Id = 29,
                            Brand = "Island Packet Yachts",
                            Description = "Jacht Island Packet 420 wyprodukowany w 2000 roku o długości 12.80m.",
                            Length = 12.80m,
                            LoanPricePerDay = 1000L,
                            Name = "Island Packet 420",
                            PictureUrl = "/images/products/jacht29.jpg",
                            Price = 850000L,
                            QuantityInStock = 1,
                            Type = "Żaglowo-motorowy",
                            YearOfProduction = 2000
                        },
                        new
                        {
                            Id = 30,
                            Brand = "Island Packet Yachts",
                            Description = "Jacht Island Packet 40 wyprodukowany w 1996 roky o długości 12.50m.",
                            Length = 12.50m,
                            LoanPricePerDay = 900L,
                            Name = "Island Packet 40",
                            PictureUrl = "/images/products/jacht30.jpg",
                            Price = 580000L,
                            QuantityInStock = 1,
                            Type = "Żaglowo-motorowy",
                            YearOfProduction = 1996
                        },
                        new
                        {
                            Id = 31,
                            Brand = "Irwin",
                            Description = "Jacht Irwin 52 wyprodukowany w 1986 roky o długości 15.84m.",
                            Length = 15.84m,
                            LoanPricePerDay = 1000L,
                            Name = "Irwin 52",
                            PictureUrl = "/images/products/jacht31.jpg",
                            Price = 700000L,
                            QuantityInStock = 2,
                            Type = "Żaglowo-motorowy",
                            YearOfProduction = 1986
                        },
                        new
                        {
                            Id = 32,
                            Brand = "Beneteau",
                            Description = "Jacht Beneteau Oceanis Clipper 411 wyprodukowany w 2001 roku o długości 12.77m.",
                            Length = 12.77m,
                            LoanPricePerDay = 500L,
                            Name = "Beneteau Oceanis Clipper 411",
                            PictureUrl = "/images/products/jacht32.jpg",
                            Price = 320000L,
                            QuantityInStock = 2,
                            Type = "Żaglowo-motorowy",
                            YearOfProduction = 2001
                        },
                        new
                        {
                            Id = 33,
                            Brand = "Farr",
                            Description = "Jacht Farr VOR 60 wyprodukowany w 1997 roku o długości 18.90m.",
                            Length = 18.90m,
                            LoanPricePerDay = 1000L,
                            Name = "Farr VOR 60",
                            PictureUrl = "/images/products/jacht33.jpg",
                            Price = 700000L,
                            QuantityInStock = 1,
                            Type = "Żaglowo-motorowy",
                            YearOfProduction = 1997
                        },
                        new
                        {
                            Id = 34,
                            Brand = "Atlantic",
                            Description = "Jacht Atlantic 60 wyprodukowany w 1996 roku o długości 18.59m.",
                            Length = 18.59m,
                            LoanPricePerDay = 1000L,
                            Name = "Atlantic 60",
                            PictureUrl = "/images/products/jacht34.jpg",
                            Price = 820000L,
                            QuantityInStock = 1,
                            Type = "Żaglowo-motorowy",
                            YearOfProduction = 1996
                        },
                        new
                        {
                            Id = 35,
                            Brand = "Formosa",
                            Description = "Jacht Formosa 51 wyprodukowany w 1976 roku o długości 19.50m.",
                            Length = 19.50m,
                            LoanPricePerDay = 1000L,
                            Name = "Formosa 51",
                            PictureUrl = "/images/products/jacht35.jpg",
                            Price = 600000L,
                            QuantityInStock = 1,
                            Type = "Żaglowo-motorowy",
                            YearOfProduction = 1976
                        },
                        new
                        {
                            Id = 36,
                            Brand = "Tecnomarine",
                            Description = "Jacht Tecnomarine 62 wyprodukowany w 1992 roku o długości 18.95m.",
                            Length = 18.95m,
                            LoanPricePerDay = 1000L,
                            Name = "Tecnomarine 62",
                            PictureUrl = "/images/products/jacht36.jpg",
                            Price = 520000L,
                            QuantityInStock = 1,
                            Type = "Motorowy",
                            YearOfProduction = 1992
                        },
                        new
                        {
                            Id = 37,
                            Brand = "Princess",
                            Description = "Jacht Princess 60 wyprodukowany w 1996 roku o długości 18.60m",
                            Length = 18.60m,
                            LoanPricePerDay = 1500L,
                            Name = "Princess 60",
                            PictureUrl = "/images/products/jacht37.jpg",
                            Price = 910000L,
                            QuantityInStock = 1,
                            Type = "Motorowy",
                            YearOfProduction = 1996
                        },
                        new
                        {
                            Id = 38,
                            Brand = "Hershine",
                            Description = "Jacht Hershine MIAMI 62 wyprodukowany w 1991 roku o długości 18.50m.",
                            Length = 18.50m,
                            LoanPricePerDay = 2500L,
                            Name = "Hershine MIAMI 62",
                            PictureUrl = "/images/products/jacht38.jpg",
                            Price = 600000L,
                            QuantityInStock = 1,
                            Type = "Motorowy",
                            YearOfProduction = 1991
                        },
                        new
                        {
                            Id = 39,
                            Brand = "Saxdor",
                            Description = "Jacht Saxdor 270 GTO wyprodukowany w 2023 roku o długości 8.4m.",
                            Length = 8.45m,
                            LoanPricePerDay = 2500L,
                            Name = "Saxdor 270 GTO",
                            PictureUrl = "/images/products/jacht39.jpg",
                            Price = 590000L,
                            QuantityInStock = 1,
                            Type = "Motorowy",
                            YearOfProduction = 2023
                        },
                        new
                        {
                            Id = 40,
                            Brand = "Quicksilver",
                            Description = "Jacht Quicksilver Activ 905 Weekend wyprodukowany w 2021 roku o długości 9m.",
                            Length = 9m,
                            LoanPricePerDay = 2000L,
                            Name = "Quicksilver Activ 905 Weekend",
                            PictureUrl = "/images/products/jacht40.jpg",
                            Price = 560000L,
                            QuantityInStock = 1,
                            Type = "Motorowy",
                            YearOfProduction = 2021
                        });
                });

            modelBuilder.Entity("YachtMarinaAPI.Models.Role", b =>
                {
                    b.Property<int>("RoleId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("RoleId"));

                    b.Property<string>("Rolename")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("RoleId");

                    b.ToTable("Roles");

                    b.HasData(
                        new
                        {
                            RoleId = 1,
                            Rolename = "Turysta"
                        },
                        new
                        {
                            RoleId = 2,
                            Rolename = "Żeglarz jachtowy"
                        },
                        new
                        {
                            RoleId = 3,
                            Rolename = "Jachtowy sternik morski"
                        },
                        new
                        {
                            RoleId = 4,
                            Rolename = "Kapitan jachtowy"
                        },
                        new
                        {
                            RoleId = 5,
                            Rolename = "Sternik motorowodny"
                        },
                        new
                        {
                            RoleId = 6,
                            Rolename = "Sternik motorowodny morski"
                        },
                        new
                        {
                            RoleId = 7,
                            Rolename = "Bosman"
                        },
                        new
                        {
                            RoleId = 8,
                            Rolename = "Właściciel"
                        });
                });

            modelBuilder.Entity("YachtMarinaAPI.Models.User", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("AvatarUrl")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ConfirmationToken")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("DateOfBirth")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("DateOfRegister")
                        .HasColumnType("datetime2");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("FirstName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("HashPassword")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("LastName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PublicId")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("RoleId")
                        .HasColumnType("int");

                    b.Property<string>("Username")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("VerifiedAt")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.HasIndex("RoleId");

                    b.ToTable("Users");
                });

            modelBuilder.Entity("YachtMarinaAPI.Models.Yacht", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Brand")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal>("Length")
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PictureUrl")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("ProductId")
                        .HasColumnType("int");

                    b.Property<string>("Type")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("YearOfProduction")
                        .HasColumnType("int");

                    b.Property<DateTime?>("endDate")
                        .HasColumnType("datetime2");

                    b.Property<bool>("isLoan")
                        .HasColumnType("bit");

                    b.Property<DateTime?>("startDate")
                        .HasColumnType("datetime2");

                    b.Property<int>("userId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("userId");

                    b.ToTable("Yachts");
                });

            modelBuilder.Entity("ChatUser", b =>
                {
                    b.HasOne("YachtMarinaAPI.Entities.Chat", null)
                        .WithMany()
                        .HasForeignKey("ChatsId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("YachtMarinaAPI.Models.User", null)
                        .WithMany()
                        .HasForeignKey("UsersId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("JourneyUser", b =>
                {
                    b.HasOne("YachtMarinaAPI.Models.Journey", null)
                        .WithMany()
                        .HasForeignKey("JourneysId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("YachtMarinaAPI.Models.User", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("YachtMarinaAPI.Entities.Friend", b =>
                {
                    b.HasOne("YachtMarinaAPI.Models.User", null)
                        .WithMany("Friends")
                        .HasForeignKey("UserId");
                });

            modelBuilder.Entity("YachtMarinaAPI.Entities.Invite", b =>
                {
                    b.HasOne("YachtMarinaAPI.Models.User", null)
                        .WithMany("Invites")
                        .HasForeignKey("UserId");
                });

            modelBuilder.Entity("YachtMarinaAPI.Entities.Message", b =>
                {
                    b.HasOne("YachtMarinaAPI.Entities.Chat", "Chat")
                        .WithMany("Messages")
                        .HasForeignKey("ChatId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Chat");
                });

            modelBuilder.Entity("YachtMarinaAPI.Models.BasketItem", b =>
                {
                    b.HasOne("YachtMarinaAPI.Models.Basket", "Basket")
                        .WithMany("BasketItems")
                        .HasForeignKey("BasketId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("YachtMarinaAPI.Models.Product", "Product")
                        .WithMany()
                        .HasForeignKey("ProductId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Basket");

                    b.Navigation("Product");
                });

            modelBuilder.Entity("YachtMarinaAPI.Models.Document", b =>
                {
                    b.HasOne("YachtMarinaAPI.Models.Role", "Role")
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("YachtMarinaAPI.Models.User", "User")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Role");

                    b.Navigation("User");
                });

            modelBuilder.Entity("YachtMarinaAPI.Models.Journey", b =>
                {
                    b.OwnsMany("YachtMarinaAPI.Entities.FriendJourney", "FriendsIds", b1 =>
                        {
                            b1.Property<int>("JourneyId")
                                .HasColumnType("int");

                            b1.Property<int>("Id")
                                .ValueGeneratedOnAdd()
                                .HasColumnType("int");

                            SqlServerPropertyBuilderExtensions.UseIdentityColumn(b1.Property<int>("Id"));

                            b1.Property<int>("friendId")
                                .HasColumnType("int");

                            b1.HasKey("JourneyId", "Id");

                            b1.ToTable("FriendJourney");

                            b1.WithOwner()
                                .HasForeignKey("JourneyId");
                        });

                    b.OwnsMany("YachtMarinaAPI.Entities.LineCoordinate", "LineCoordinates", b1 =>
                        {
                            b1.Property<int>("JourneyId")
                                .HasColumnType("int");

                            b1.Property<int>("Id")
                                .ValueGeneratedOnAdd()
                                .HasColumnType("int");

                            SqlServerPropertyBuilderExtensions.UseIdentityColumn(b1.Property<int>("Id"));

                            b1.Property<decimal>("Lat")
                                .HasColumnType("decimal(18,2)");

                            b1.Property<decimal>("Lng")
                                .HasColumnType("decimal(18,2)");

                            b1.HasKey("JourneyId", "Id");

                            b1.ToTable("LineCoordinate");

                            b1.WithOwner()
                                .HasForeignKey("JourneyId");
                        });

                    b.OwnsMany("YachtMarinaAPI.Entities.Marker", "Markers", b1 =>
                        {
                            b1.Property<int>("JourneyId")
                                .HasColumnType("int");

                            b1.Property<int>("Id")
                                .ValueGeneratedOnAdd()
                                .HasColumnType("int");

                            SqlServerPropertyBuilderExtensions.UseIdentityColumn(b1.Property<int>("Id"));

                            b1.Property<decimal>("Lat")
                                .HasColumnType("decimal(18,2)");

                            b1.Property<decimal>("Lng")
                                .HasColumnType("decimal(18,2)");

                            b1.HasKey("JourneyId", "Id");

                            b1.ToTable("Marker");

                            b1.WithOwner()
                                .HasForeignKey("JourneyId");
                        });

                    b.OwnsMany("YachtMarinaAPI.Entities.Photo", "PhotosUrls", b1 =>
                        {
                            b1.Property<int>("JourneyId")
                                .HasColumnType("int");

                            b1.Property<int>("Id")
                                .ValueGeneratedOnAdd()
                                .HasColumnType("int");

                            SqlServerPropertyBuilderExtensions.UseIdentityColumn(b1.Property<int>("Id"));

                            b1.Property<string>("Url")
                                .IsRequired()
                                .HasColumnType("nvarchar(max)");

                            b1.HasKey("JourneyId", "Id");

                            b1.ToTable("Photo");

                            b1.WithOwner()
                                .HasForeignKey("JourneyId");
                        });

                    b.Navigation("FriendsIds");

                    b.Navigation("LineCoordinates");

                    b.Navigation("Markers");

                    b.Navigation("PhotosUrls");
                });

            modelBuilder.Entity("YachtMarinaAPI.Models.Order.Order", b =>
                {
                    b.OwnsOne("YachtMarinaAPI.Models.Order.ShippingAddress", "ShippingAddress", b1 =>
                        {
                            b1.Property<int>("OrderId")
                                .HasColumnType("int");

                            b1.Property<string>("Address1")
                                .IsRequired()
                                .HasColumnType("nvarchar(max)");

                            b1.Property<string>("City")
                                .IsRequired()
                                .HasColumnType("nvarchar(max)");

                            b1.Property<string>("FullName")
                                .IsRequired()
                                .HasColumnType("nvarchar(max)");

                            b1.Property<string>("State")
                                .HasColumnType("nvarchar(max)");

                            b1.Property<string>("Zip")
                                .HasColumnType("nvarchar(max)");

                            b1.HasKey("OrderId");

                            b1.ToTable("Orders");

                            b1.WithOwner()
                                .HasForeignKey("OrderId");
                        });

                    b.Navigation("ShippingAddress")
                        .IsRequired();
                });

            modelBuilder.Entity("YachtMarinaAPI.Models.User", b =>
                {
                    b.HasOne("YachtMarinaAPI.Models.Role", "Role")
                        .WithMany()
                        .HasForeignKey("RoleId");

                    b.Navigation("Role");
                });

            modelBuilder.Entity("YachtMarinaAPI.Models.Yacht", b =>
                {
                    b.HasOne("YachtMarinaAPI.Models.User", "User")
                        .WithMany("Yachts")
                        .HasForeignKey("userId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("YachtMarinaAPI.Entities.Chat", b =>
                {
                    b.Navigation("Messages");
                });

            modelBuilder.Entity("YachtMarinaAPI.Models.Basket", b =>
                {
                    b.Navigation("BasketItems");
                });

            modelBuilder.Entity("YachtMarinaAPI.Models.User", b =>
                {
                    b.Navigation("Friends");

                    b.Navigation("Invites");

                    b.Navigation("Yachts");
                });
#pragma warning restore 612, 618
        }
    }
}
